### ISSUE TITLE
Is send Invoice request working?

### ISSUE THREAD

**Issue by mortezaa** [Jooyeshgar/moadian#1]
We have some problems in sending invoices . is it right? make an example for working better with sending invoices please. 
Thanks

**Comment by hadi60** [comment]
Yes, our sending invoice feature is functional, but it has not been fully tested yet. I have updated the README file with an example. Please ensure that you are using version 0.5.

**Comment by mortezaa** [comment]
@hadi60  Do you successfully sent an invoice and is it shown in your Moadian panel?

**Comment by hadi60** [comment]
Yes, but not exactly with this code. we need about a week to do final test and release version 1.0

**Comment by hadi60** [comment]
@mortezaa It's work you can use version 1.0
