### ISSUE TITLE
Error 400 BAD_REQUEST "4212"

### ISSUE THREAD

**Issue by maxebi** [Jooyeshgar/moadian#10]
سلام خدمت شما و تشکر بابت زحماتتون
بعد از اینکه آپدیت کردم زمانی که استعلام میگیرم این ارور رو برمیگردونه مشکل از خود سامانه است یا جای دیگه ای میتونه ایراد داشته باشه
ممنون میشم راهنمایی کنید
![Screenshot 1402-03-30 at 22 50 58](https://github.com/Jooyeshgar/moadian/assets/23015955/f96f6b83-b83b-45c2-9610-322f45e31fcd)

**Comment by hadi60** [comment]
سلام
من بعد از آپدیت یکی فرستادم و مشکلی نداشت فقط PENDING می زنه که ظاهرا مشکل از سامانه است
داخل خود پنل هم بری می بینی که تو هواست
درواقع دیتاها رو فرستادی رفرنس رو گرفتی؟
به نظرم چند روزی صبر کن
