### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by mailed91** [Jooyeshgar/moadian#11]
سلام
بعد از اینکه مرحله pending رو پشت سرگذاشتیم الان با 405 مواجه میشیم در هرکدوم از رکویست ها

**Comment by hadi60** [comment]
شما مرحله 400 رو از دست دادی :D
#10

**Comment by maxebi** [comment]
دوستان سلام الان شما بعد آپدیت تونستید صورت حساب ارسال کنید یا همچنان ارور دارید؟

**Comment by CyberDepot** [comment]
> دوستان سلام الان شما بعد آپدیت تونستید صورت حساب ارسال کنید یا همچنان ارور دارید؟

سلام، من به شخصه تو مرحله ارور 400 هستم
جوری سامانه رو ترکوندن که تو قسمت code دارن message بر میگردونن (400 BAD_REQUEST "4212")

**Comment by CyberDepot** [comment]
خلاصه اینکه دست به گیرنده های خود نزنین که مشکل از فرستنده هست :)

**Comment by mailed91** [comment]
به نظرم منطقی نیست پس چجوری معتمد ها میفرستن؟

**Comment by hadi60** [comment]
سامانه تازه درست شده
حالا منم چک می کنم خبر می دم

**Comment by hbhossein** [comment]
سلام یک فاکتور فرستادیم و response که گرفتیم فعلا این هست:
Server error: `POST https://tp.tax.gov.ir/req/api/self-tsp/sync/GET_TOKEN` resulted in a `503 Service Temporarily Unavailable` 
مثل که اینکه فعلا از دسترس خارج هست

**Comment by nasser-sahebi** [comment]
سلام دوستان
در 4-5 روز گذشته موفق شدید موردی ارسال کنید؟ یا اطلاعی دارید که معتمد ها میتونن بفرستن یا نه؟ ما همچنان 400 میگیریم؟

**Comment by hadi60** [comment]
نه سامانه به نظر خراب می یاد هر دفعه یه حالیه
ارسال می شه ها موقع استعلام اشتباه بر می گردونه

**Comment by hadi60** [comment]
البته تو پنل هم نمی شینه

**Comment by nasser-sahebi** [comment]
تشکر @hadi60، دقیقا رفرس کد میده ولی استعلام خطا داره و در پنل نمیشه

**Comment by mailed91** [comment]
موفق به ارسال و استعلام شدید؟
هنوز 4212 bad request میگیریم

**Comment by hadi60** [comment]
مشکل از clientId بود نشست توی کارپوشه
سیستم هم به نظر درسته
آپدیت کنید ورژن v1.1.1

تغییرات
https://github.com/Jooyeshgar/moadian/compare/v1.1...v1.1.1

**Comment by hadi60** [comment]
مشکل حل شد؟

**Comment by nasser-sahebi** [comment]
بله، تشکر، مشکل رفع شد، ارسال انجام شد و در کارپوشه ثبت شد
یک سوال خارج از موضوع issue، امکان ویرایش اطلاعات ارسالی وجود داره؟

**Comment by hadi60** [comment]
با ثبت فاکتور اصلاحی و یا فاکتور ابطالی
در حسابداری معمولا چیزی به عنوان ویرایش وجود نداره هر اصلاحی بک سند جدید به حساب می یاد برای انکه سوابق ویرایش کاملا مشخص باشه
