### ISSUE TITLE
ثبت سند اصلاحیه

### ISSUE THREAD

**Issue by na5sa** [Jooyeshgar/moadian#12]
سلام
من با هر روش و مقداری سند اصلاحیه ثبت می‌کنم خطا می‌گیرم، کسی موفق شده ثبت کنه؟ امکانش هست یک نمونه ارسال در این issue قرار بدین؟
`
{"code":"0301","message":"مقدار فیلد «شماره مالیاتی صورتحساب» با اطلاعات سامانه منطبق نیست.","errorType":"ERROR"}
`
تشکر

**Comment by mailed91** [comment]
> سلام من با هر روش و مقداری سند اصلاحیه ثبت می‌کنم خطا می‌گیرم، کسی موفق شده ثبت کنه؟ امکانش هست یک نمونه ارسال در این issue قرار بدین؟ `{"code":"0301","message":"مقدار فیلد «شماره مالیاتی صورتحساب» با اطلاعات سامانه منطبق نیست.","errorType":"ERROR"}` تشکر

این خطا مربوط به فیلد inno هستش با این تابع جنریتش کن اما موجودیت این تابع هیچ ربطی به مستندات نداره و من درآوردی هستش.
`public function generate($length = 10): string
    {
        if (function_exists("random_bytes")) {
            $bytes = random_bytes(ceil($length / 2));
        } elseif (function_exists("openssl_random_pseudo_bytes")) {
            $bytes = openssl_random_pseudo_bytes(ceil($length / 2));
        } else {
            throw new Exception("no cryptographically secure random function available");
        }
        return substr(bin2hex($bytes), 0, $length);
    }`

**Comment by hadi60** [comment]
البته اینکه سامانه دوباره ظاهرا مشکل داره رو هم در نظر بگیر

فانکشن رو بازش کردم که پیدا باشه
اگه حل شد خبر بده تا تو کد اضافه کنیم
چون نمی تونیم سند اصلاحی بزنیم در واقع اکانت واقعیه اون تستی رو نداریم
```php
public function generate($length = 10): string {
	if (function_exists("random_bytes")) {
		 $bytes = random_bytes(ceil($length / 2));
	}
	elseif (function_exists("openssl_random_pseudo_bytes")) { 
		$bytes = openssl_random_pseudo_bytes(ceil($length / 2));
	} 
	else { 
		throw new Exception("no cryptographically secure random function available"); 
	}
	return substr(bin2hex($bytes), 0, $length); 
}
```

**Comment by aghasi** [comment]
> سلام من با هر روش و مقداری سند اصلاحیه ثبت می‌کنم خطا می‌گیرم، کسی موفق شده ثبت کنه؟ امکانش هست یک نمونه ارسال در این issue قرار بدین؟ `{"code":"0301","message":"مقدار فیلد «شماره مالیاتی صورتحساب» با اطلاعات سامانه منطبق نیست.","errorType":"ERROR"}` تشکر

صورتحساب مرجع به سامانه قدیم (قبل 26 خرداد 1402) ارسال کردید؟

**Comment by na5sa** [comment]
ممنون بابت راهنمایی @hadi60  @mailed91 
تغییر سریال صورتحساب یا inno مشکلی ایجاد نمیکنه؟ حتما در جریان هستین که سیستم سنتی دارایی روی توالی این سریال حساس هستش و اگر این تغییر روی فاکتور اصلی لحاظ بشه شاید مشکل ساز بشه، چک میکنم

**Comment by na5sa** [comment]
> > سلام من با هر روش و مقداری سند اصلاحیه ثبت می‌کنم خطا می‌گیرم، کسی موفق شده ثبت کنه؟ امکانش هست یک نمونه ارسال در این issue قرار بدین؟ `{"code":"0301","message":"مقدار فیلد «شماره مالیاتی صورتحساب» با اطلاعات سامانه منطبق نیست.","errorType":"ERROR"}` تشکر
> 
> صورتحساب مرجع رو به سامانه قدیم (قبل 26 خرداد 1402) ارسال کردید؟

خیر، صورتحساب مربوط به سامانه جدید هست

**Comment by mailed91** [comment]
شماهم این خطا رو میگیرید؟
-statusCode: 200
  -error: null
  -body: array:1 [
    0 => array:6 [
      "referenceNumber" => "d3feeb0c-9175-480a-964a-57b6627e1eeb"
      "uid" => "ab76d4b5-7944-41b3-8630-55500621ec80"
      "status" => "FAILED"
      "data" => array:4 [
        "confirmationReferenceId" => null
        "error" => array:1 [
          0 => array:3 [
            "code" => "400 BAD_REQUEST "4200""
            "message" => "400 BAD_REQUEST "4200""
            "errorType" => "ERROR"
          ]
        ]
        "warning" => []
        "success" => false
      ]
      "packetType" => "error"
      "fiscalId" => "A12KON"
    ]
  ]

**Comment by mailed91** [comment]
سامانه مشکل جدی داره
همه سر کاریم به نظر میرسه
یا دادن دست چارتا کار آموز براشون نوشته یا یه سرور ابری تستی گذاشتن پشتش
علی برکت اله

**Comment by mailed91** [comment]
> ممنون بابت راهنمایی @hadi60 @mailed91 تغییر سریال صورتحساب یا inno مشکلی ایجاد نمیکنه؟ حتما در جریان هستین که سیستم سنتی دارایی روی توالی این سریال حساس هستش و اگر این تغییر روی فاکتور اصلی لحاظ بشه شاید مشکل ساز بشه، چک میکنم

این برای تسته برای واقعی یه الگوریتم بزن که ده رقم جنریت کنه و order داشته باشه میتونی از شماره فاکتورت استفاده کنی و پشتش هر تعداد کاراکتر نیاز داره صفر بزاری و اولش 1

**Comment by hadi60** [comment]
الان این مشکل هست یا درسته شده؟

به نظرم بیایم ویکی رو راه بندازیم. یه چند تا اموزش این جوری داخلش بزاریم مردم از این سردر گمی در بیان
