### ISSUE TITLE
خطا در زمان دریافت توکن

### ISSUE THREAD

**Issue by beyzad-asa** [Jooyeshgar/moadian#13]
سلام و روز بخیر.

دوستان من از ابتدا تا همین الان توی متد دریافت توکن مشکل داشتم. کدی هم که خودم نوشتم دقیقا همین خطا رو داشت. گفتم شاید یه جایی از کار من اشتباه بوده. از این کلاس که استفاده میکنم هم دقیقا همین خطا رو دارم میگیرم. واقعا کلافه شدم.

`امضای بسته صحیح نمیباشد`

نمیدونم دلیلش چیه. از صحت کلید هم اطمینان دارم.. شما به چنین موردی برخورد نکردین؟

**Comment by hadi60** [comment]
سلام
کدهای ما رو اگه داری استفاده می کنی درسته چون داره کار می کنه
البته برای ارسال invoice ظاهرا مشکل داره داره pending می ده دوباره
احتمالا توی ساختن امضا، ارسال توی پنل و تاییدش توسط دفاتر خدماتی مشکل داری همه رو براسال روال های خودش رفتی؟
تایید شده امضا توسط دفاتر خدماتی؟

**Comment by beyzad-asa** [comment]
> سلام کدهای ما رو اگه داری استفاده می کنی درسته چون داره کار می کنه البته برای ارسال invoice ظاهرا مشکل داره داره pending می ده دوباره احتمالا توی ساختن امضا، ارسال توی پنل و تاییدش توسط دفاتر خدماتی مشکل داری همه رو براسال روال های خودش رفتی؟ تایید شده امضا توسط دفاتر خدماتی؟

بله. از کد شما هم که استفاده میکنم این خطا رو دارم. مراحل ساخت کلید رو هم طی فیلمهای آموزشی سایت https://csr.orash.ir/ که دوستان عزیز زحمت کشیدن تهیه کردن انجام دادم.

والا من هم متهم اصلی رو کلیدها میدونم. اما چند مرتبه صفر تا صد رو چک کردم و همه چیز درست بود. مگر اینکه ابزاری که دوستان توی سایت بالا گذاشتن ایراد داشته باشه و کلیدهام از بیخ و بن مشکل داشته باشن.

**Comment by beyzad-asa** [comment]
با سلام.
خواستم اطلاع بدم که متاسفانه ایراد از همون کلید ها بود و با تولید و ثبت کلید جدید مشکل برطرف شد.
سپاس
