### ISSUE TITLE
در صورتحساب ارسالی فیلد «clientId» غیرمجاز است.

### ISSUE THREAD

**Issue by amirajlo** [Jooyeshgar/moadian#14]
سلام
الان هر درخواستی که من ارسال میکنم
پس از پردازش این ارور رو نشون میده 

با کد:017701 
در صورتحساب ارسالی فیلد «clientId» غیرمجاز است.

و 
در صورتحساب ارسالی فیلد «payment» غیرمجاز است.

**Comment by mailed91** [comment]
سلام
آپدیت کن پکیج رو

**Comment by mailed91** [comment]
> سلام الان هر درخواستی که من ارسال میکنم پس از پردازش این ارور رو نشون میده
> 
> با کد:017701 در صورتحساب ارسالی فیلد «clientId» غیرمجاز است.
> 
> و در صورتحساب ارسالی فیلد «payment» غیرمجاز است.

سلام
آپدیت کن پکیج رو

**Comment by amirajlo** [comment]
> 

آپدیت کردم. همون مشکل رو داره - بعضی درخواست هام هم pending میمونه

**Comment by aghasi** [comment]
> > 
> 
> آپدیت کردم. همون مشکل رو داره - بعضی درخواست هام هم pending میمونه
مشکل pending  از سمت شما نیست. و مشکل از سامانه مودیان هست.

**Comment by hadi60** [comment]
ظاهرا رندم بعضی ها انجام می شه ها بعضی ها هم پندیگ
