### ISSUE TITLE
کد اقتصادی برای اشخاص حقیقی

### ISSUE THREAD

**Issue by alitalaghat** [Jooyeshgar/moadian#15]
سلام دوستان

زمانی که در متد `getEconomicCodeInformation` کد ملی یک شخص حقیقی رو وارد میکنم، خطای زیر رو دریافت میکنم.
``` 
array(3) {
      ["code"]=>
      string(22) "400 BAD_REQUEST "5207""
      ["message"]=>
      string(22) "400 BAD_REQUEST "5207""
      ["errorType"]=>
      string(5) "ERROR"
    }
```
با توجه به خطای بالا آیا این امکان وجود دارد که کد ملی رو به عنوان `tinb` برای شخص حقیقی ثبت کنم؟ اگر نه چه کاری برای ثبت فاکتور برای شخص حقیقی باید انجام بدیم؟

**Comment by mailed91** [comment]
> سلام دوستان
> 
> زمانی که در متد `getEconomicCodeInformation` کد ملی یک شخص حقیقی رو وارد میکنم، خطای زیر رو دریافت میکنم.
> 
> ```
> array(3) {
>       ["code"]=>
>       string(22) "400 BAD_REQUEST "5207""
>       ["message"]=>
>       string(22) "400 BAD_REQUEST "5207""
>       ["errorType"]=>
>       string(5) "ERROR"
>     }
> ```
> 
> با توجه به خطای بالا آیا این امکان وجود دارد که کد ملی رو به عنوان `tinb` برای شخص حقیقی ثبت کنم؟ اگر نه چه کاری برای ثبت فاکتور برای شخص حقیقی باید انجام بدیم؟

داکیومنت رو بخون توضیح داده خلاصه میگم:
مقدار tob اگر حقیقی بود 1 در غیر اینصورت 2 شایدم برعکس بگم یادم نیست دقیقا.
اگر حقیق بود tinb و bid رو هردو کد ملی بزن
یاحق

**Comment by aghasi** [comment]
> سلام دوستان
> 
> زمانی که در متد `getEconomicCodeInformation` کد ملی یک شخص حقیقی رو وارد میکنم، خطای زیر رو دریافت میکنم.
> 
> ```
> array(3) {
>       ["code"]=>
>       string(22) "400 BAD_REQUEST "5207""
>       ["message"]=>
>       string(22) "400 BAD_REQUEST "5207""
>       ["errorType"]=>
>       string(5) "ERROR"
>     }
> ```
> 
> با توجه به خطای بالا آیا این امکان وجود دارد که کد ملی رو به عنوان `tinb` برای شخص حقیقی ثبت کنم؟ اگر نه چه کاری برای ثبت فاکتور برای شخص حقیقی باید انجام بدیم؟

سلام 
اول اینکه کد اقتصادی اشخصاص حقیقی همون کد ملی شون نیست. کد ملی 10 رقم هست و همونطور که اسناد میگه کد اقتصادی اشخاص حقیقی 14 رقمی هست.
 بهترین راه برای بدست آوردن کد اقتصادی حقیقی اینه که از خودشون بگیرید که اونها هم باید داخل پنل my.tax.gov.ir ببینن. مقدار رو باید در tinb قرار بدید.
راه حایگزین اینه که به انتهای سمت راست کد ملی، چهار رقم اضافه کنید و با حالتهای مختلف که از 0001 شروع میشه  و یکی یکی بالا میره تست کنید. اگه استعلام getEconomicCodeInformation جواب داد که میتونید ازش استفاده کنید. دقت کنید که ممکنه یه کد ملی چنتا کد اقتصادی داشته باشه (مثلا یه رستوران داشته باشه یه نانوایی) و این روش خیلی هم خوب نیست. در هر صورت مقداری که در این راه بدست میاد داخل tinb بزارید.
یه راه دیگه اینه که از ترکیب کد ملی و کد پستی استفاده کنید. tinb رو نال بزارید و کد ملی داخل bid و کد پستی داخل bpc. در این حالت با ترکیب این دو سامانه مودیان سعی میکنه خودش کد اقتصادی خریدار رو پیدا کنه و صورتحساب رو بزاره داخل کارپوشه اگه مشخصاتی که شما وارد میکنید اشتباه باشه (به هر دلیلی) کارپوشه پیدا نمیشه و در نتیجه صورتحساب به داخل کارپوشه خریدار نمیره. در نتیجه اعتبار مالیاتی اون برای خریدار قابل استفاده نیست. انگار اینکه شما برای مصرف کننده نهایی صورتحساب صادر کرده باشید. تقریبا نصف صورتحسابهایی که ما تا الان صادر کردیم برای مشتری هامون اینطوری بوده.

یه نکته در مورد اشخاص حقیقی حواستون باشه که تعداد بالایی از اشخاص حقیقی اصلا پرونده مالیاتی ندارند. یعنی فرار مالیاتی دارند (در واقع از اهداف اصلی سامانه مودیان شناسایی اینها هست). قطعا این افراد کارپوشه ندارند پس صورتحساب به کارپوشه شون نمیره که به ضرر خودشون هست و جریمه یا مشکلی برای فروشنده ایجاد نمیکنه.
