### ISSUE TITLE
400 Bad Request "4212"

### ISSUE THREAD

**Issue by mailed91** [Jooyeshgar/moadian#16]
با سلام
پس از ارسال صورتحساب و دریافت ReferenceNum جهت استعلام صورتحساب خطای زیر برمگیرده.

<img src="https://user-images.githubusercontent.com/23015955/247239055-f96f6b83-b83b-45c2-9610-322f45e31fcd.png" />

**Comment by mailed91** [comment]
مشکل از کلید عمومی بود که به معتمد وصل بود

**Comment by hadi60** [comment]
مشکل اینه که pending می ده بعضی ها رو
