### ISSUE TITLE
رند کردن مقدار ارزش افزوده

### ISSUE THREAD

**Issue by alitalaghat** [Jooyeshgar/moadian#17]
سلام دوستان

در مستندات نوشته شده که مبلغ ارزش افزوده نمیتونه اعشار داشته باشه. با توجه به این موضوع در زمان محاسبه ارزش افزوده مبلغ رو چطور باید رند کنیم؟ به بالا یا به پایین؟

مثلا برای محصولی با قیمت ۵۳۲۲ ریال ارزش افزوده ۴۷۸.۹۸ ریال هست.

ممنون میشم اگر تجربه ای در این مورد دارید با من به اشتراک بگذارید.

**Comment by mailed91** [comment]
> سلام دوستان
> 
> در مستندات نوشته شده که مبلغ ارزش افزوده نمیتونه اعشار داشته باشه. با توجه به این موضوع در زمان محاسبه ارزش افزوده مبلغ رو چطور باید رند کنیم؟ به بالا یا به پایین؟
> 
> مثلا برای محصولی با قیمت ۵۳۲۲ ریال ارزش افزوده ۴۷۸.۹۸ ریال هست.
> 
> ممنون میشم اگر تجربه ای در این مورد دارید با من به اشتراک بگذارید.

سلام وقت بخیر به پایین رند کن
