### ISSUE TITLE
"detail": "امضای بسته صحیح نمی باشد", "errorCode": "4011"

### ISSUE THREAD

**Issue by mmdt12** [Jooyeshgar/moadian#18]
سلام.
من با nodejs میخوام از api های سامانه مودیان استفاده کنم و مراحلی که شما توی sdk لاراولتون برای گرفتن توکن زدید رو پیاده کردم تو برنامم اما به این اررور برخوردم. ممنون میشم راهنمایی کنید.

**Comment by hadi60** [comment]
یا کلید رو درست ثبت نکردی توی سامانه یا روش امضا کردن درست نیست
می تونی یه بسته رو هر دو طف امضا کنی ببینی کجا مشکل داره
با توجه به اینکه مربوط به کدهای ما نیست می بندم تیکت رو
