### ISSUE TITLE
مشکل در چک کردن طول کد مالیاتی

### ISSUE THREAD

**Issue by CyberDepot** [Jooyeshgar/moadian#2]
با تشکر از جنابعالی بابت این پکیج
در متد getEconomicCodeInformation شرط چک کردن طول می بایست به این صورت تغییر کند

~~~php
if (strlen($taxID) < 9 || strlen($taxID) >= 12)
~~~

**Comment by hadi60** [comment]
ممنون از اطلاع
برطرف شد در ورژن بعدی خواهد بود
