### ISSUE TITLE
Error 5202 in inquiry by reference number

### ISSUE THREAD

**Issue by mmdt12** [Jooyeshgar/moadian#21]
من صورتحساب رو ارسال کردم و Reference number رو دریافت کردم.
از INQUIRY_BY_REFERENCE_NUMBER که استفاده میکنم این جواب رو دریافت میکنم و مشکلم اینجاست که داخل ارور ننوشته با چی مشکل داره!!!!:

{
    "signature": null,
    "signatureKeyId": null,
    "timestamp": 1691823674622,
    "result": {
        "uid": null,
        "packetType": "INQUIRY_RESULT",
        "data": [
            {
                "referenceNumber": "7afd3aaf-00e2-414c-9941-b4d56684d3b1",
                "uid": "15d955ed-67f9-47f3-9a71-680ab8d615f5",
                "status": "FAILED",
                "data": {
                    "confirmationReferenceId": null,
                    "error": [
                        {
                            "code": "400 BAD_REQUEST \"5202\"",
                            "message": "400 BAD_REQUEST \"5202\"",
                            "errorType": "ERROR"
                        }
                    ],
                    "warning": [],
                    "success": false
                },
                "packetType": "error",
                "fiscalId": "******"
            }
        ],
        "encryptionKeyId": null,
        "symmetricKey": null,
        "iv": null
    }
}

**Comment by hadi60** [comment]
دقیق یادم نیست که بد ریکوئست مال چی بود ولی معمولا فیلد ها اشتباه هستن یا امضا اشتباه 
اگه از کدهای ما استفاده می کنی نباید این خطا رو بگیری باید خطاهای لایه محتوی رو بگیری که بهتر توضیح داده خظا چیه
این یه خطا است در مورد خود بسته
بقیه توابع کار می کنن؟
از کدهای ما استفاده کردی؟

**Comment by hadi60** [comment]
یه لاراول هم بیار بالا خروجی کد ما رو با خروجی کد خودت مقایسه کن فکر کنم توی امضای بسته توی انکودینگش مشکل داشته باشی
ما هم یه مدت همین مشکل رو داشتیم انکودینگی که می خواست رو php پشتیبانی نمی کرد یه کتابخونه اضافه کردیم
طبق تجربه می گم چون لایه محتوی رو خیلی بهتر خطا می ده توی داکیومنت هم نوشته خطای general انگار این bad request رو
این قسمت تنها قسمتیه که اون انکودینگ امضا و اینا رو می خواد به همین خاطر که اون ها کار می کنه این خطا می ده

**Comment by mmdt12** [comment]
`{
  "Authorization": "Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJBMkFSM1ciLCJ0b2tlbklkIjoiMGQzOGM3MzMtZDA1NS00OGVhLWEwNmUtYzU2ZDM2Yzk0YTNlIiwiY3JlYXRlRGF0ZSI6MTY5MjAxNzIzOTEwMiwiY2xpZW50VHlwZSI6Ik1FTU9SWSIsInRheHBheWVySWQiOiIxMDM4MDU2NTQ0NyIsInN1YiI6IkEyQVIzVyIsImV4cCI6MTY5MjAzMTYzOSwiaXNzIjoiVEFYIE9yZ2FuaXphdGlvbiJ9.NopNAZ4a541ikiRqJqmPbfVP5URmRNqvZ_fxAUYCRxKZy0WTQr5EcnVVrq9ooO-q2KD02d5A-kQFqgzvZItCTw",
  "requestTraceId": "facba833-1b83-4702-ab35-1fff71aaf2fe",
  "timestamp": 1692017803309,
  "packets": [
    {
      "uid": "f8c71e4b-1f13-4dc5-be68-c9fce7e3eb7c",
      "packetType": "INVOICE.V01",
      "retry": false,
      "data": "bqhmH1o+pSVHDOIkHy1mxzqpxSIjRkWOBukvUuzPwk6VAZYRdOWvW84QgBSEcByVfTHDRXu47wJ//Cxi7cf75iJodLdU05xc2nHLVoNT+ajkDtzp6BxjuzbwBvOyqn9Y9redn4b7TaAUoURSUuYSUm5/W/oaQjs/rpRnOhccfy4fCRmxemiM8oNm/Cl1Bty97b095nwoVpPEBASIR02rXdznwd8AuCRh2/3VLY1TmqTiJSyfS8heq+U5VDU+aW2QPgVoPKch11spoZYWAT3qZKm/onsYho0sUBcDdN2WmL4R53Cd8ziyodCg00yuwNzn5EIXxDLBJzPo1Ozx1fygKWITBwE/2LTZtdUFQt+XLaH5PGY1asekfXh378hC9noTyMKerMdyEkmx3udCFHVOLfQcjCWmewcdT0TVjfcKkWvLltSoJfLGN4NItPr9H9fl3MoyYf0iqY0E7j2r7KGbbj4L6mdrVbMca1jMIaJ9tFoyjSz+AaIPraATz6e64+zFWU4E0ii20YDAV83nU3wUKy7IN95mrqqY4rXT8H1Uz9o34lOADv6tgQt2Zn2BFlv7+QEyLQSyBDIu8MN6aAKJsAKvy8W6pYCsSaZZRmviC2dvx2z36B9ZsxV3aJhMl95honxtUZnsYGVYxN2I6elK/Xkax+RDEKt7bKrUu19SSRqMciZaX1HfnQcQ4lZWuZIJx4U5B4EqJO9Jug3GJ+HVjfhzfmIluxRQtJgNlAbnSwHBUyC6pLqea+3gpdja7TuHSCqy4n09YO2cTxfE1puXEealSgYbpXLk/EWXbgPkpyzi+5GlKew+4wMK/oGPB4TaRUodGh27GbAo3CcnafJQC8Zdl1iEgGJLRAHlIVhElacWPLEeDVDlO5bhhoN3nS3SNhc2Yd51/fuNXzIaASKL44md9pDF/rnEUqH37ODeTW59w0qf8jq4yKhw+SrCXk7+4rVQaQXTs9/BukDYded7YFYvPDcAVTF9qJ+V/bEpkEYe5jz20xQqN5jlUvYwUG4Cr8nJAIHp9e+5kaQpyMEFqP/1UyKQG51L/0aLTZIw254viuxya23zAqvXLDNqBihfl5wniQ7UgM+WKzA/GqmH3KZPeZSZ9QB9NrtTH5wKu6WA9x7EQ/ksP17g8Lu0t+hcJsbfW8dVmyZOtWEDVANuz549a7n1bHzpizg83pyK4YWFUXyzraNsQZO99Fxu9rPytLGul6gVwJPkU8k6A6eKhnHDDFkDzJJNykiwOPV4A6lkhCWk8E719TdU8rLhV7JcDhUVAVu5bUBFjNirI29hnnU/RCDxmiXpT1eNXhefjGCUB98/BjJ/6+qgXRR3nopXhaNddXLCjB9k8d7iLlTp7BUj68p4SItpkPiISq11XFtI",
      "dataSignature": "ktypxVDQH3FYdW40dzknRqmneUJb1d+ALdBwb5LWLy7PNtBzwUTiyyFgQZ0USvmYqsWc1jzv4pTeZVsGfCtbG3F15focR1iXOE3vzpIoq+84ijdaJNHEdBg6u25n4HnAciEJh5rna5DN3Ywz8NPgHX07WPfXY9n0sEmopy83B3+t22AN32rtYL5tS2I073VBxMeXGPeLKw/vkV9b7U5lBC3xc4BRgtC3Q10h46bwM4eFaoupfdPRlvzBMFTgQboDTVZIrWa7BAbTuCp83/OoGy8F2q54kj9XHDR7+Iv66wPD0DYnWRAQfR86K9FoxDgRvGUAjq9QIAFxPpGhDC2LAg==",
      "fiscalId": "******",
      "encryptionKeyId": "6a2bcd88-a871-4245-a393-2843eafe6e02",
      "iv": "e5af64dc000593b5109889ad960f89fd",
      "symmetricKey": "Ydj8Dm4EEeYoNenDvvgBw3u47mtyT1FkXCMcLpe6Us6NJFPdfalj/5ooBQmGUCCq5mjnLrpOCMphm4sbTytpoLlX55WJeTdup7sg9BIHDzrWzT9RM4G139ZArSyi/npPJZYa0Ta32wL0aKVdk8rnTHJQLh8CEOCyPIQw5JPe9irnRkbaWiGRSxYW2zAc2KEY1Q43R9a73h9Nn8AQYAyLwaPwSXHZjhI9Eys2W8KWQyqpqrLWnhiDGjamW8S6RRtoUX0TW7aCA01LGQbcMZrG9EKbngIduXtSo4GPqrtO4oNV/Hdn1KZypoCI3pL0P8p/xn+UejLUJU5o9aw3nwthTD/aiwM1+ARAsCL8GHlbHYtQ4Apkn64jqMM12GjGCfRD+Hcn5/Q1B+IuuaEVg855fJIOaXgXNKOWSKxQ3OKv6uHfQPnRXiMN/isYetNwM7NIa3dez7sCZBs+GWwgeGeJwELueiA6SJiYRY7/ByLxhN5daj8IKptpYOk0u7qnTsLdltOQ/cZ/Cb1kIQ4fkOFGdLolCKDBy7i5hvKrL8zp0TlOrsYDi/PY9nfBbgN6QLbFXkjHk4tadZp5bmeLK7Okw8S2PJ9wwD6DYcl3CP5VG4hsDf4k9p8Ao4ojaEaOuAfwjcM7G0GzGVkQW164wg2wDzYkryyB5R/Y1pwHKKtA554="
    }
  ],
  "signature": "Fwxe2xgMJAFX+EM9W4nGeD5m6AI1y06brKEZMbbKMzCPyiyTBE2dhRrLgiIOXfhrOy1I0qZpXXwTTuNEqqK/vDbH3uiQyQ2ltmW8ToFrwRrIuwFfqXWuG2xnBjFpEvTjVuDLXJDVNTb9oO+eYXhD2P0KWwj5XAezqoNvfXHW2i6M5kz7wcNA5jDh/+OCLnmGtd3HvanilfrRDbSd8Io82dBlATwijVYm6xPiLFZOXYrHGPNec/6KlYNKdO/fiGIyBn39GMGIgBXEUgBq3tKRdrXav2zlPekQ/G3n+EK0BvrFoXQMvMBRGAYQarFmvYU0IJC+mAYLHzFr5PHQkmYLHg=="
}`

ببینید این دیتا ارسالی منه، و دوتا سوال:
* اون iv وقتی hex میشه 32 کاراکتر میشه یا 64؟
* امضا ها (signature) اگر غلط باشند خب ریکوعست های دیگم به مشکل برمیخورند چون همشون امضا دارند

**Comment by mmdt12** [comment]
خب الان با کلی تغییر به ارور 4212 رسیدم.... اگر نظری در این مورد دارید ممنون میشم 
@hadi60

**Comment by mmdt12** [comment]
این اررو به رمز گزاری کلید متقارن ( symmetricKey) بر میگشت
