### ISSUE TITLE
قابلیت جدید

### ISSUE THREAD

**Issue by 30namp** [Jooyeshgar/moadian#23]
سلام
وقت شما بخیر
اگر میشه برای این پروژه قابلیت دریافت اطلاعات کالا و شناسه ها از سامانه مودیان را هم بذارید
البته اگر بخواید خود من هم میتونم در توسعه این پروژه به شما کمک کنم و هیچ هزینه ای هم دریافت نمیکنم
و بازم ممنون که این پروژه رو درست کردید و خیلیا رو از شر اون api .Net نجات دادید 👌

به زودی هم یک آپدیت دارند و بنظرم بهتر که حواسمون به اون هم باشه
مثل اینکه قرار خیلی چیزها تغییر پیدا کنه

**Comment by mmdt12** [comment]
@hadi60 
@hbhossein 

آقا دیروز زده ترکونده سامانه مودیان... فیلد اضافه کرده... inquiryرو عوض کرده... دریابید.

**Comment by hbhossein** [comment]
سلام
تغییرات نسخه دوم سامانه مودیان به پروژه اضافه شد. یک فاکتور با نسخه جدید ارسال کردیم که در پنل ثبت شد. اما در بعضی از responseها مشکلاتی وجود دارد (مثل null بودن response) که بعد از برطرف شدن ان و تست کامل نسخه دوم منتشر می شود.

**Comment by mmdt12** [comment]
@hbhossein 
اگر امکانش هست نحوه گرفتن توکن رو کدش رو بذارید

**Comment by hadi60** [comment]
شما از اینجا می تونی تمامی کدها و کامیت ها رو ببینی

https://github.com/Jooyeshgar/moadian/tree/update-to-v2

**Comment by mmdt12** [comment]
@hadi60 
@hbhossein 
آقا من توی توکن موندم باز... همش اینو دریافت میکنم (توی ریکوعست server-info) داررم دیوانه میشم.... 3روزه علافشم :(

{
    "timestamp": 1696941834004,
    "requestTraceId": null,
    "errors": [
        {
            "code": "4131",
            "message": "امضای توکن JWT یا گواهی امضای فرستاده شده معتبر نمی‌باشد."
        }
    ]
}

نظری ندارید؟؟

**Comment by hbhossein** [comment]
بدون کد سخت هست که مشکل را پیدا کرد اما چند مورد را درنظر داشته باشین:
مطمئن بشید header و payload توکن دقیقا بر اساس داکیومنت خود سامانه باشه. مثلا فیلد sigT حتما همون فرمت باشه٫ گواهی امضا باید داخل ارایه باشه نه یک رشته و ...
اگه برای  تولید توکن از پکیج استفاده میکنین احتمالا مقدار بعضی از فیلدها را در header تغییر میده (مشکلی که ما هم داشتیم و مقدار typ را از jose به jwt تغییر میداد)
برای تست هم میتونین داده های داکیومنت را به کدتون بدین و باید دقیقا همون توکن تولید بشه.

**Comment by mmdt12** [comment]
```
const crypto = require("crypto");
const fs = require('fs');
const key = fs.readFileSync('./2.key', 'utf-8')
const cert = fs.readFileSync('./2.crt', 'utf-8').replaceAll('\r\n', '')

console.log(generateToken( 'A11226', key, cert, '942a1ccd-a6a5-47f6-8e80-a92358cc11a1'));

function generateToken(fiscalId, key, cert, nonce) {
    const header = {
        alg: 'RS256',
        x5c: [cert],
        sigT: "2023-05-13T10:44:47Z",
        typ: 'jose',
        crit: ['sigT'],
        cty: 'text/plain'
    }
    const encodeHeader = Buffer.from(JSON.stringify(header)).toString('base64url');

    const payload = {
        nonce: nonce,
        clientId: fiscalId
    }
    const encodePayload = Buffer.from(JSON.stringify(payload)).toString('base64url');

    const signature = sign(encodeHeader, encodePayload, key);

    return encodeHeader + '.' + encodePayload + '.' + signature;
}

function sign(jwtB64Header, jwtB64Payload, privateKey) {
    const signer = crypto.createSign('SHA256');
    signer.update(jwtB64Header + '.' + jwtB64Payload);
    signer.end();
    return signer.sign(privateKey, "base64url");
}
```

این کد ساخت توکنمه که جالبیش اینجاست داده های داکیومنت رو میدم و خروجی داکیومنت رو هم میگیرم... ولی هم باکلید و سرتیفیکیت خودمون تست کردم و هم با ماله خودشون بازم همون اررور رو میده

**Comment by hbhossein** [comment]
اگه از همین function برا گرفتن توکن استفاده میکنید مشکل مقدار فیلد sigT در header هست که باید زمان امضای بسته باشه یعنی تابع زمان حال را بخونه و به این فرمت داخل فیلد sigt قرار بده
@mmdt12

**Comment by mmdt12** [comment]
آره... توی کد اصلی مقدارsigT  زمان حال رو میخونه ... اینجا برای نمونه اینطوری نوشتم... در واقع چیزی که میبینید مقادیر داکیومنت هست که دادم به تابع ... درواقع اصلش هدر به این صورته
` 
const header = {
            alg:'RS256',
            x5c:[cert],
            sigT:new Date().toISOString().split('.')[0]+"Z",
            typ:'jose',
            crit:['sigT'],
            cty:'text/plain'
        }
`

من اگر بخوام مشکلمو دقیق خدمتون شرح بدم، مشکل اینه که من وقتی توکن رو ایجاد میکنم و از ای پی آی های نیاز به احراز هویت مثل همین سرور اینفو که استفاده میکنم، بعضی وقتا ریسپانس رو برمیگردونه و بعضی وقتا هم ایراد میگیره از توکن.. البته 70 درصد مواقع ایراد میگیره و 30 درصد مواقع اوکی میده

@hadi60
