### ISSUE TITLE
Class "Firebase\JWT\JWT" not found

### ISSUE THREAD

**Issue by maxebi** [Jooyeshgar/moadian#24]
چطور میتونم این کتابخانه رو اضافه کنم به پروژه که این خطارو نداشته باشم؟

**Comment by hadi60** [comment]
با خود composer باید این کارو بکنی تا دیپندنسی هاش رو هم اضافه کنه
احتمالا دستی اضافه کردی

**Comment by maxebi** [comment]
> با خود composer باید این کارو بکنی تا دیپندنسی هاش رو هم اضافه کنه احتمالا دستی اضافه کردی

وقتی دستور composer require jooyeshgar/moadian رو اجرا میکنم ورژن 1.1 اضافه میشه من ورژن 2.0.0 رو بخوام استفاده کنم باید چیکار کنم

**Comment by hadi60** [comment]
چون هنوز مطمئن نبودیم beta است باید minimum-stability رو کمتر کنی 

"minimum-stability": "beta",
