### ISSUE TITLE
مشکل در گرفتن اطلاعات سرور

### ISSUE THREAD

**Issue by maxebi** [Jooyeshgar/moadian#25]
پس از آپدیت به نسخه جدید ( 2.0.0-beta ) من این ارور رو دارم : 
 GuzzleHttp\Exception\ClientException: Client error: `GET https://tp.tax.gov.ir/requestsmanager/api/v2/server-information` resulted in a `401 Unauthorized` response:
{"timestamp":1698602306361,"requestTraceId":"febd2e96e8a52dc98e5d20accac6b09c","errors":[{"code":"Unable to load certifi (truncated...)
آیا این خطا برای معتبر نبودن گواهی امضاست ؟ 
گواهی امضا رو باید از چه طریق دریافت کنم ؟
نمونه فرمت گواهی امضا به چه شکلیه ؟

**Comment by hadi60** [comment]
بله به نظرم
گواهی امضار و می تونی از اینجا بگیری https://www.gica.ir/
برای راهنما
https://www.intamedia.ir/The-regulation-of-store-terminals/ID/15879/%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C-%D8%A7%D8%B3%D8%AA%D8%AE%D8%B1%D8%A7%D8%AC-%DA%A9%D9%84%DB%8C%D8%AF-%D8%B9%D9%85%D9%88%D9%85%DB%8C-%D8%A7%D8%B2-%D8%A7%D9%85%D8%B6%D8%A7%DB%8C-%D8%AF%DB%8C%D8%AC%DB%8C%D8%AA%D8%A7%D9%84%D9%85%D9%87%D8%B1%D8%B3%D8%A7%D8%B2%D9%85%D8%A7%D9%86%DB%8C-%D9%88-%D8%A8%D8%A7%D8%B1%DA%AF%D8%B0%D8%A7%D8%B1%DB%8C-%D8%A2%D9%86-%D8%AF%D8%B1-%DA%A9%D8%A7%D8%B1%D9%BE%D9%88%D8%B4%D9%87-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%85%D9%88%D8%AF%DB%8C%D8%A7%D9%86
