### ISSUE TITLE
کانفیگ کد با آدرس sandbox

### ISSUE THREAD

**Issue by mreza9** [Jooyeshgar/moadian#26]
سلام. چطوری می تونم از این کد با آدرس sandboxrc.tax.gov.ir استفاده کنم؟ در کلاس Moadian یک baseurl و privatekey قراردادید... ولی نمی توان آنها را از کنترلر تغییر داد. در صورت امکان راهنمایی فرمایید و یا آنها را اصلاح کنید. ممنون

**Comment by hbhossein** [comment]
سلام
میتوانید baseUri را با استفاده از MOADIAN_BASE_URI داخل فایل env تغییر دهید.( با استفاده از اخرین ورژن پکیج )

**Comment by mreza9** [comment]
با سلام. ممنون از پاسخ شما
در کنترلر کلاس اصلی را صدا زدم و یک کلاس جدید بدین شکل از آن ساختم. با این کار دیگری نیازی به قراردادن در env هم نبود. 

use Jooyeshgar\Moadian\Moadian as Mo;
 $mo = new Mo($fiscalid, $privatekey, 'https://sandboxrc.tax.gov.ir/');
