### ISSUE TITLE
عدم استفاده از certificate

### ISSUE THREAD

**Issue by abbasgholia** [Jooyeshgar/moadian#27]
سلام. من قبلا بدون گواهی امضا ( certificate ) با سند باکس استفاده می کردم ولی الان اجباری شده این فایل.
من نمی خوام با certificate  ارسال کنم. امکانش هست؟
راستی تغییرات جدید هم نداره در مستندات سامانه مودیان مالیات

**Comment by hadi60** [comment]
سلام
راستش هیچ راهنمایی برای سند باکس نبود و کسی رو هم پیدا نکردیم که در مورد سندباکس به ما اطلاعاتی بده حتی url اش رو هم همین جا از بقیه شنیدیم 
ما خودمون داریم با گواهی امضا و اطلاعات واقعی تست می کنیم 
این که در سند باکس می شه بدون certificate فرستاد یا نه رو باید از خود اداره دارایی بپرسید یا با تست به دست بیارید
