### ISSUE TITLE
سلام بروز خطای Dependency 

### ISSUE THREAD

**Issue by majidalamdary** [Jooyeshgar/moadian#28]
سلام برای دریافت اطلاعات سرور این خطا رو میده
Unresolvable dependency resolving [Parameter #0 [ <required> $privateKey ]] in class Jooyeshgar\Moadian\Moadian
کد من:
        $privateKey = file_get_contents(__DIR__ . '/private.key');
        $certificate = file_get_contents(__DIR__ . '/cert.cer');
        $moadian = new Moadian($privateKey,$certificate);
        $info = $moadian->getServerInfo();

**Comment by hadi60** [comment]
پارامتر اول نام کاربری و پارامتر دوم privateKey فرمت رو هم داری اشتباه می دی
```
            $privateKeyPath = $config['private_key_path'] ?? storage_path('app/keys/private.pem');
            $privateKey = file_get_contents($privateKeyPath);

            return new Moadian(
                $config['username'],
                $privateKey
            );
```
