### ISSUE TITLE
کلاس MoadianInvoice

### ISSUE THREAD

**Issue by CyberDepot** [Jooyeshgar/moadian#3]
کلاس MoadianInvoice در پکیج وجود ندارد
لطفا در خصوص این کلاس توضیح دهید
در صورت امکان همانند بقیه مدل ها به پکیج اضافه گردد

**Comment by CyberDepot** [comment]
کلاس وجود داره، ALias شده بود و من متوجه نشدم
use Jooyeshgar\Moadian\Invoice as MoadianInvoice;

**Comment by hadi60** [comment]
به خاطر اینه که ما خودمون هم یه مدل اینویس داشتیم برای اینکه اشتباه نشه Alias کردیم :D
داشتم فکر می کردم یه ایمیل هم اومده بود در باره این کلاس پس چرا تو ایشو ها نیست :D

**Comment by CyberDepot** [comment]
ممنونم، بله متوجه شدم، بابت این پکیج هم ازت ممنونم، واقعا داکیومنتی که امور
مالیاتی داده افتضاح به تمام معنا هست، دم شما گرم که متوجه شدی و نوشتیش

‫‪Hadi‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۵ مه ۲۰۲۳ ساعت
۱۵:۱۲ نوشت:‬
