### ISSUE TITLE
Error 0202

### ISSUE THREAD

**Issue by aghasi** [Jooyeshgar/moadian#4]
میخام فاکتور فروش مربوط به اواسط فروردین 1402 رو ارسال کنم اما این خطا رو میده:
```
"error" => array:1 [
          0 => array:3 [
            "code" => "0202"
            "msg" => "مقدار فیلد تاریخ و زمان صدور صورتحساب از لحاظ قواعد محاسباتی و منطقی معتبر نمی باشد و صورتحساب معتبر نیست."
            "detail" => []
          ]
        ]
```

تا حدود یکماه قبل رو موفق ارسال میکنه ولی این تاریخی که من میخوام رو نه.

**Comment by hadi60** [comment]
اگر اشتباه نکنم توی داکیومنت حداکثر یک هفته اجازه می ده ولی در عمل تا یک ماه رو می تونی ارسال کنی در واقع محدودیت خود سامانه است به کدهای ما مربوط نمی شه
در واقع این خطا های لایه محتوی است و به api مربوط نمی شن
