### ISSUE TITLE
به روز رسانی 27 خرداد 1402

### ISSUE THREAD

**Issue by CyberDepot** [Jooyeshgar/moadian#7]
سلام
طبق مستندات RC_IITP.IS _V6.4 به روز رسانی 27 خرداد 1402، کلاس ها رو به این صورت تغییر دادم که خدمتتون ارسال می کنم

عنصر payment به payments تغییر پیدا کرده است، لطفا کلاس را به صورت زیر اصلاح نمایید

```php
<?php

namespace Jooyeshgar\Moadian;

class Invoice
{
    private InvoiceHeader $header;
    private array $body = [];
    private array $payments = [];

    public function __construct(InvoiceHeader $header)
    {
        $this->header = $header;
    }

    public function addItem(InvoiceItem $item)
    {
        $this->body[] = $item;
    }

    public function addPayment(Payment $payment)
    {
        $this->payments[] = $payment;
    }

    public function toArray()
    {
        return [
            'header'  => $this->header->toArray(),

            'body'    => array_map(function ($item){
                return $item->toArray();
            }, $this->body),

            'payments' => array_map(function ($item){
                return $item->toArray();
            }, $this->payments),

            'extension' => null,
        ];
    }
}

```

در Header هم بابت ارسال clientID خطا می دهد که به اینصورت اصلاح کردم، لطفا اعمال نمایید

```php
<?php

namespace Jooyeshgar\Moadian\Http;

use Jooyeshgar\Moadian\Invoice;

class invoicePacket extends Packet
{
    public function __construct(string $username, Invoice $invoice) {

        parent::__construct();

        $this->path        = 'req/api/self-tsp/async/normal-enqueue';
        $this->packetType  = 'INVOICE.V01';
        $this->fiscalId    = $username;
        $this->needToken   = true;
        $this->needEncrypt = true;
        $this->data = $invoice->toArray();

        unset($this->data['header']['clientId']);
    }
}

```
  
این موارد شامل پکیج شما نمیشه، صرفا جهت اطلاع رسانی به دوستان میگم
  
  
- در خطاها و هشدارهای بازگشتی از سامانه مودیان مقدار msg به message تغییر داده شده است
- همچنین عنصر details از خطاها حذف شده است
- واحد های اندازه گیری به روز رسانی شده است
  
  
مستندات مربوطه رو پیوست می کنم
  
  
  
  
  
[RC_IITP.IS _V6.4.pdf](https://github.com/Jooyeshgar/moadian/files/11779648/RC_IITP.IS._V6.4.pdf)
[RC_TXME.RD_v02.pdf](https://github.com/Jooyeshgar/moadian/files/11779649/RC_TXME.RD_v02.pdf)
[سند واحدهای اندازه گیری 1402-03-07_1.pdf](https://github.com/Jooyeshgar/moadian/files/11779650/1402-03-07_1.pdf)

**Comment by hadi60** [comment]
یه برنج ساختم کد ها رو گذاشتم داخلش
این retry رو کلا حذف کردن از invoice؟ چرا این قدر بد نوشتن داکیومنت رو از کجا بفهمم چی تغییراتی دادن :D
حالا فردا دقیق تر چک می کنم

**Comment by CyberDepot** [comment]
والا منم مثل شما اسیر شدم، چهار روز مونده به انتهای فصل مالی که اومدن آپدیت دادن
باز گفتم بزارم اینجا که همه استفاده کنن
  
منظورت از retry رو متوجه نشدم کجا هست، یاد جلسه امتحان ریاضی افتادم، از جلسه اومدیم بیرون بچه ها درباره سوال 15 بحث میکردن، من گفتم حاجی دوازده تا سوال بیشتر که نبود، یکی گفت بقیش پشت برگه بود :| حالا بگو ببینم این retry کجاست؟

**Comment by hadi60** [comment]
خوب حاجی دارم کلی به خودم فشار می یارم که چرا اینو حذف کردن چرا از همه جا حذف نکرده :D
اینجا رو ببین
https://github.com/Jooyeshgar/moadian/compare/main...7-update-27-3-1402#diff-bc0e7822012669ff5f6bf693b7d46040edb2a6edcfcd49e56123839716b4d252L19

فایل اولی خط ۱۹

**Comment by CyberDepot** [comment]
من تو پکیجی که دارم اصلا این خط رو ندارم

$this->retry = $invoice->retry;
داستانش چیه؟

**Comment by CyberDepot** [comment]
من چند تا اختلاف با نسخه شما دارم
یکی اینکه در فایل InvoiceItem.php من $vam رو اختیاری در نظر گرفتم، اما شما اجباری
طبق مستندات کدوم صحیح است؟

در فایل من یک شرط در قسمت defined('CHARACTER_TO_NUMBER_CODING') گذاشتم، چون بهم خطا میداد که قبلا تعریف شده

و در نهایت در invoicePacket.php مقدار زیر رو اضافه کردم
```
$this->retry       = $invoice->retry;
```

**Comment by hadi60** [comment]
مقدار ارزش افزودست که باید باشه
تو قسمت 7-42 مبلغ مالیات بر ارزش افزوده گفته اجباری

برای اون خطا هم شاید دوبار InvoiceHeader رو صدا می زنی
می خوای شرط رو بده منم اضافه کنم

**Comment by hadi60** [comment]
اون retry رو جوری که من فهمیدم اگر فرستادی و مشکل داشت دوباره خواستی بفرستی باید true باشه
